version: '3.9'

services:
  #app:
  #  container_name: hospital
  #  build: 
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - 8080:8080
  #  restart: on-failure
  #  depends_on:
  #    - postgres
  #  links:
  #    - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 6543:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=Hospital111
      - POSTGRES_USER=wallog
      - POSTGRES_DB=hospital
  
  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redis:/data

volumes:
  postgres:
  redis: